### PR TITLE
Change in font of Heading

### PR DESCRIPTION
**Pull request by yeshijinsel**

### CODE REVIEW

**Comment by shirshak55** [comment]
@yeshijinsel  would be please add those fonts and import it.

**Comment by yeshijinsel** [comment]
ok

**Comment by yeshijinsel** [comment]
but which font 
is it( https://fonts.google.com/specimen/Varela+Round?selection.family=Varela+Round ) this one

**Comment by shirshak55** [comment]
Yes you can use any font you like but let it be cool and from opensource.

**Comment by shirshak55** [comment]
@yeshijinsel  this is not html only bro. It is a mikrotik router template. So we cannot include using link tag. Hope you understand. And thanks for your interest. There a couple of problems in the codebase which you can clearly see. Thanks

**Pull request closed without merging**
